name: Bug Report
description: Create a bug report for Hawa UI Kit
labels: ['template: bug']
body:
  - type: markdown
    attributes:
      value: |
        This template is to report Next.js bugs. [Examples](https://github.com/vercel/next.js/tree/canary/examples) related issues should be reported using [this](https://github.com/vercel/next.js/issues/new?assignees=&labels=type%3A+example%2Ctemplate%3A+bug&template=2.example_bug_report.yml) issue template instead.
        Feature requests should be opened as [discussions](https://github.com/vercel/next.js/discussions/new?category=ideas). [Read more](https://github.com/vercel/next.js/blob/canary/contributing/core/adding-features.md).

        Before opening a new issue, please do a [search](https://github.com/vercel/next.js/issues) of existing issues and :+1: upvote the existing issue instead. This will result in a quicker resolution.

        If you need help with your own project, you can:
        - Start a discussion in the ["Help" section](https://github.com/vercel/next.js/discussions/categories/help)
        - Ask a question on the [Next.js Discord](https://discord.com/invite/nextjs) server
  - type: input
    attributes:
      label: Link to the code that reproduces this issue or a replay of the bug
      description: |
        A link to a **public** [GitHub repository](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template) or a [CodeSandbox](https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template) minimal reproduction. Minimal reproductions should be created from our [bug report template with `npx create-next-app -e reproduction-template`](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template) and should include only changes that contribute to the issue. To report a Pages Router related issue, you can use these templates: [`npx create-next-app -e reproduction-template-pages`](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template-pages) or [CodeSandbox](https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-pages)

        If a minimal reproduction can't be created, please share a [replay](https://www.replay.io/) of the bug which doesn't require sharing a private repo.

        **Skipping this/providing an invalid link will result in the issue being closed**
      placeholder: 'https://github.com/user/my-minimal-nextjs-issue-reproduction'
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, based on the linked reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
      placeholder: |
        1. Start the application in development (next dev)
        2. Click X
        3. Y will happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: A clear and concise description of what the bug is, and what you expected to happen.
      placeholder: 'Following the steps from the previous section, I expected A to happen, but I observed B instead'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Verify canary release
      description: 'Please run `npm install next@canary` to try the canary version of Next.js that ships daily. It includes all features and fixes that have not been released to the stable version yet. Some issues may already be fixed in the canary version, so please verify that your issue reproduces before opening a new issue.'
      options:
        - label: I verified that the issue exists in the latest Next.js canary release
          required: true
  - type: textarea
    attributes:
      label: Provide environment information
      description: Please run `next info` in the root directory of your project and paste the results. You might need to use `npx --no-install next info` if next is not in the current PATH.
      render: bash
      placeholder: |
        Operating System:
          Platform: darwin
          Arch: arm64
          Version: Darwin Kernel Version 22.5.0
        Binaries:
          Node: 18.17.1
          npm: 9.5.1
          Yarn: 1.22.19
          pnpm: N/A
        Relevant Packages:
          next: 13.4.20
          eslint-config-next: 13.4.20
          react: 18.2.0
          react-dom: 18.2.0
          typescript: 5.2.2
        Next.js Config:
          output: N/A
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - 'Not sure'
        - 'App Router'
        - 'CLI (create-next-app)'
        - 'Data fetching (gS(S)P, getInitialProps)'
        - 'Dynamic imports (next/dynamic)'
        - 'ESLint (eslint-config-next)'
        - 'Font optimization (next/font)'
        - 'Image optimization (next/image, next/legacy/image)'
        - 'Internationalization (i18n)'
        - 'Jest (next/jest)'
        - 'MDX (@next/mdx)'
        - 'Metadata (metadata, generateMetadata, next/head)'
        - 'Middleware / Edge (API routes, runtime)'
        - 'Operating System (Windows, MacOS, Linux)'
        - 'Package manager (npm, pnpm, Yarn)'
        - 'Routing (next/router, next/navigation, next/link)'
        - 'Script optimization (next/script)'
        - 'Standalone mode (output: "standalone")'
        - 'Static HTML Export (output: "export")'
        - 'SWC minifier (swcMinify: true)'
        - 'SWC transpilation'
        - 'Turbopack (--turbo)'
        - 'TypeScript (plugin, built-in types)'
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Another way you can help the maintainers' job is to pinpoint the `canary` version of `next` that introduced the issue. Check out our [releases](https://github.com/vercel/next.js/releases), and try to find the first `canary` release that introduced the issue. This will help us narrow down the scope of the issue, and possibly point to the PR/code change that introduced it. You can install a specific version of `next` by running `npm install next@<version>`.
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate. For example, where are you deploying your application (Vercel, Docker, other platform)? Is it only reproducible on that platform, or locally too? Is the issue only happening in a specific browser? etc.
      placeholder: |
        I tested my reproduction against different canary releases, and the first one that introduced the bug was "13.4.20-canary.13", since reverting to "13.4.20-canary.12" works.

        or

        I am hosting via Docker with the recommended `output: "standalone"` option", and if I remove that option or try a different hosting option, I cannot reproduce the same issue.