// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  default: {
    "login-form-demo": {
      name: "login-form-demo",
      type: "components:example",
      registryDependencies: ["accordion"],
      component: React.lazy(() => import("@/registry/demos/login-form-demo")),
      files: ["registry/demos/login-form-demo.tsx"]
    },
    "register-form-demo": {
      name: "register-form-demo",
      type: "components:example",
      registryDependencies: ["accordion"],
      component: React.lazy(
        () => import("@/registry/demos/register-form-demo")
      ),
      files: ["registry/demos/register-form-demo.tsx"]
    },
    "contact-form-demo": {
      name: "contact-form-demo",
      type: "components:example",
      registryDependencies: ["accordion"],
      component: React.lazy(() => import("@/registry/demos/contact-form-demo")),
      files: ["registry/demos/contact-form-demo.tsx"]
    },
    "app-layout-demo": {
      name: "app-layout-demo",
      type: "components:example",
      registryDependencies: ["accordion"],
      component: React.lazy(() => import("@/registry/demos/app-layout-demo")),
      files: ["registry/demos/app-layout-demo.tsx"]
    },
    "accordion-demo": {
      name: "accordion-demo",
      type: "components:example",
      registryDependencies: ["accordion"],
      component: React.lazy(() => import("@/registry/demos/accordion-demo")),
      files: ["registry/demos/accordion-demo.tsx"]
    },
    "toast-demo": {
      name: "toast-demo",
      type: "components:example",
      registryDependencies: ["toast"],
      component: React.lazy(() => import("@/registry/demos/toast-demo")),
      files: ["registry/demos/toast-demo.tsx"]
    },
    "alert-demo": {
      name: "alert-demo",
      type: "components:example",
      registryDependencies: ["alert"],
      component: React.lazy(() => import("@/registry/demos/alert-demo")),
      files: ["registry/demos/alert-demo.tsx"]
    },
    "alert-customized-demo": {
      name: "alert-customized-demo",
      type: "components:example",
      registryDependencies: ["alert"],
      component: React.lazy(
        () => import("@/registry/demos/alert-customized-demo")
      ),
      files: ["registry/demos/alert-customized-demo.tsx"]
    }
  }
};
