#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Change to use `git diff --cached --name-only` to only check staged changes.
declare COMPONENTS_CHANGED=$(git diff --cached --name-only | grep 'packages/components')

# Run `tsc` if changes are detected in the respective directories
if [[ $COMPONENTS_CHANGED ]]; then
    pushd packages/components && tsc --noEmit || exit 1
    popd
fi
