name: Hawa Build and Publish on Push

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          if [ -e 'package-lock.json' ]; then 
           npm ci
          else 
           npm install
          fi
      - name: Build Library
        run: npm run build-up
      - name: Build Styles
        run: npm run build:styles
      - name: Generate Tailwind Styles
        run: npm run generate-css
      - name: Publish to NPM
        run: npm publish

  deploy:
    needs: build
    runs-on: [self-hosted, linux, x64, sikka-sofware-server-development]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Change working directory to ./landing
        run: cd ./landing
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Hawa Landing
        run: |
          rm -fr /home/cloudpanel/htdocs/hawa.style || true
          cd /var/www/html/sikka-software/_work/Hawa/Hawa/landing
          rm -fr package-lock.json || true
          rm -fr node_modules  || true
          npm install
          npm run build --if-present
          ln -s /var/www/html/sikka-software/_work/Hawa/Hawa/landing /home/cloudpanel/htdocs/hawa.style
          pm2 stop hawa-landing || true
          pm2 delete hawa-landing || true
          pm2 start npm --name "hawa-landing" -- start || true
