name: Hawa CI - @beta

env:
  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_PUBLISH_TAG: next # Specify the tag for publishing (make sure to change it in the append -beta as well)

on:
  push:
    branches: [main]

jobs:
  publish-package:
    if: ${{!contains(github.event.head_commit.message, 'skip_publish')}}
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux, x64, a01]
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Append -next to package.json version
        run: |
          node -e "const fs = require('fs'); const packageJson = require('./package.json'); packageJson.version += '-next'; fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2));"

      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Build Library
        run: npm run build-lib
      - name: Generate Tailwind Styles
        run: npm run build-css
      - name: Publish to NPM @next tag
        run: npm publish --tag $NPM_PUBLISH_TAG # Specify the tag here

  deploy-landing:
    if: ${{ contains(github.event.head_commit.message, 'deploy_landing') }}

    runs-on: [self-hosted, linux, x64, a01]
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          path: deploy-landing-path
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Hawa Landing
        run: |
          rm -fr /home/cloudpanel/htdocs/hawa.style || true
          cd /var/www/html/sikka/actions_runner/_work/Hawa/Hawa/deploy-landing-path
          rm -fr package-lock.json || true
          rm -fr node_modules  || true
          npm install
          npm run build --if-present
          ln -s /var/www/html/sikka/actions_runner/_work/Hawa/Hawa/deploy-landing-path /home/cloudpanel/htdocs/hawa.style
          pm2 stop hawa-landing || true
          pm2 delete hawa-landing || true
          pm2 start npm --name "hawa-landing" -- start || true
          pm2 save || true

  build-storybook:
    if: ${{ !contains(github.event.head_commit.message, 'skip_storybook') }}
    runs-on: [self-hosted, linux, x64, a01]
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          path: build-storybook-path
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate Storybook Static Files
        run: |
          cd /var/www/html/sikka/actions_runner/_work/Hawa/Hawa/build-storybook-path
          rm -fr package-lock.json || true
          npm install
          npm run build-storybook
