name: Hawa CI - @beta

env:
  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_PUBLISH_TAG: next # Specify the tag for publishing (make sure to change it in the append -beta as well)
  NODE_VERSION: "21.x"
  PM2_PATH: /www/server/nvm/versions/node/v20.11.0/bin/pm2
  PNPM_PATH: /www/server/nodejs/v20.11.0/bin/pnpm

on:
  push:
    branches: [main]

jobs:
  publish-package:
    runs-on: [self-hosted, linux, x64, A01]
    steps:
      - uses: actions/checkout@v2
      - name: Append -next to package.json version
        run: |
          node -e "const fs = require('fs'); const packageJson = require('./package.json'); packageJson.version += '-next'; fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2));"
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.0
          run_install: false
      - name: Install dependencies
        run: ${{ env.PNPM_PATH }} install
      - name: Build Library
        run: ${{ env.PNPM_PATH }} run build:lib
      - name: Publish to NPM @next tag
        run: ${{ env.PNPM_PATH }} --filter @sikka/hawa publish --no-git-checks --tag $NPM_PUBLISH_TAG # Specify the tag here
