name: Hawa CI - @latest

env:
  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  release:
    types:
      - created

jobs:
  publish-package:
    runs-on: [self-hosted, linux, x64, A01]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.0
          run_install: false

      - name: Install dependencies
        run: pnpm install
      - name: Build Library
        run: pnpm run build:lib
      - name: Publish to NPM
        run: pnpm --filter @sikka/hawa publish --no-git-checks
